### ISSUE TITLE
Implement ping/pong on event stats websockets

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus-super-heroes#111]
Currently the websockets in the event stats service don't implement ping/pong, so after a while the browser drops the websocket connection. When this happens the user needs to refresh the page.

This would need to be implemented on the server side ([`TeamStatsWebSocket`](https://github.com/quarkusio/quarkus-super-heroes/blob/main/event-statistics/src/main/java/io/quarkus/sample/superheroes/statistics/endpoint/TeamStatsWebSocket.java) & [`TopWinnerWebSocket`](https://github.com/quarkusio/quarkus-super-heroes/blob/main/event-statistics/src/main/java/io/quarkus/sample/superheroes/statistics/endpoint/TopWinnerWebSocket.java)) as well as on the client ([`index.html`](https://github.com/quarkusio/quarkus-super-heroes/blob/main/event-statistics/src/main/resources/META-INF/resources/index.html)).

**Comment by jgrecu** [comment]
Hi Eric,

This is the first time I am contributing to any (non personal) project.
I want to do this, how do I start?

Thank you.

P.S. we chatted about a bit on the DubJUG meeting, a week ago.

**Comment by edeandrea** [comment]
Hi @jgrecu ! Thanks for wanting to contribute!

So the current issue is that if you bring up the [Statistics UI](https://github.com/quarkusio/quarkus-super-heroes/tree/main/event-statistics) and leave the browser window open for a while (couple of minutes - I don't know off the top of my head what the actual timeout is), then the websocket becomes disconnected.

The browser will terminate the connection due to inactivity. You have to reload the browser window to re-establish the WebSocket connection.

The [WebSocket API has the concept of pings & pongs](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API/Writing_WebSocket_servers#pings_and_pongs_the_heartbeat_of_websockets) used to keep WebSocket connections alive between a client (a browser in this case) and a server. The WebSocket client should send `ping` frames and the server should respond with `pong` frames.

As implemented today, the event statistics does not implement this.

Now I'm no WebSocket expert or anything, but part of this ticket might be to see if there is something within Quarkus (or the Quarkiverse) which already implements this. Maybe its simple and we're just missing some configuration?

Or maybe we need to implement it ourselves. Implementing it will most likely have 2 parts - the server implementation & the client implementation. The server implementation will happen in the `event-statistics` project, most likely in `io.quarkus.sample.superheroes.statistics.endpoint.EventStatsWebSocket`. The client implementation will most likely be in the Javascript code (`event-statistics/src/main/resources/META-INF/resources/index.html`).

Part of this ticket will be investigating what the proper implementation is.

My own opinion here, but maybe something like this belongs directly in the `quarkus-websockets` extension? If so, that would mean starting a conversation on the Quarkus repo and trying to direct the work there. If you decide to go down that route, probably starting a discussion or opening an issue on the Quarkus repo would be the next step. If you do that, linking this ticket to that would be good for tracking purposes.

If its deemed that the implementation should be done inside a client application, there are some resources I've found that may be helpful (https://dzone.com/articles/ping-pong-implementation-jsr-356 for example). But it may be that you need to figure out what the appropriate approach is (and then write tests as well!).

Does that help?

**Comment by edeandrea** [comment]
I opened quarkusio/quarkus#31157 for this as well.

**Comment by jgrecu** [comment]
ohh, thank you very much @edeandrea was scratching my head which repo to do it. 👍🏼

**Comment by edeandrea** [comment]
So I think what we do here in this issue depends heavily on the outcome of that one I opened.

If Quarkus itself ends up implementing the pong in the websocket extension, then this issue just becomes implementing the ping in the JavaScript UI.

**Comment by edeandrea** [comment]
I think for now we need to wait and see what comes out of that issue I created in Quarkus. What happens there will certainly drive what needs to be done here.
