### ISSUE TITLE
Document how to use Jaeger

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-super-heroes#116]
In the README file we need to document how to use Jaeger

see #115

**Comment by edeandrea** [comment]
I actually have a whole blog post about it coming out (hopefully) in the next 2 weeks.

**Comment by agoncal** [comment]
Cool, we will be able to link the readme to it. But in this case is just how to use Jaeger to display the Super Heroes traces (with a few screenshots to help)

**Comment by edeandrea** [comment]
Yup my post will have all of that.

Maybe we should have a separate README for the monitoring stack and how to use it. The current README is pretty long.

**Comment by agoncal** [comment]
It's up to you, I quite like a long single HTML page to follow along
