### ISSUE TITLE
Azure super heroes is broken on new postgres change

### ISSUE THREAD

**Issue by roryp** [quarkusio/quarkus-super-heroes#134]
The single script version for super heroes is broken on https://github.com/quarkusio/quarkus-super-heroes/blob/main/docs/deploying-to-azure-containerapps.md - there was a change for the protocol for postgres to include open telemetry and now the villains app cant connect to the database

Exception: 
error 11:12:08 ERROR traceId=, parentId=, spanId=, sampled= [or.hi.en.jd.sp.SqlExceptionHelper] (JPA Startup Thread: <default>) Driver does not support the provided URL: jdbc:postgresql://villains-db-codespace.postgres.database.azure.com:5432/villains?ssl=true&sslmode=require

**Comment by edeandrea** [comment]
See #133 - this will fix that.

Until that gets merged if you want to fix it manually you can modify the script to change

```
VILLAINS_DB_CONNECT_STRING="jdbc:otel:postgresql://${VILLAINS_DB}.postgres.database.azure.com:5432/${VILLAINS_DB_SCHEMA}?ssl=true&sslmode=require"
```
