### ISSUE TITLE
Using Kotlin in any of the samples?

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus-super-heroes#143]
Should we use any Kotlin anywhere?

**Comment by edeandrea** [comment]
@cescoffier @agoncal What do you think?

**Comment by hbzhou** [comment]
I tried to follow the guide and  coded with kotlin here, just for reference https://github.com/hbzhou/quarkus-kotlin-super-heroes

**Comment by edeandrea** [comment]
Thank you @hbzhou for sharing!
