### ISSUE TITLE
add instructions on how generate the JS models based on the OpenAPI

### ISSUE THREAD

**Issue by rafaeltuelho** [quarkusio/quarkus-super-heroes#172]
It looks like the models for the UI were auto-generated using Swagger CodeGen. It would be nice to have this step documented in the UI's readme.

**Comment by edeandrea** [comment]
@agoncal gentle ping...

**Comment by agoncal** [comment]
Yes, it's documented in the [initial Super Hero workshop](https://github.com/quarkusio/quarkus-workshops/tree/main/quarkus-workshop-super-heroes/super-heroes/ui-super-heroes#swagger-codegen). At the time we used Swagger Codegen and generated the models and services in the Angular app with:

```
https://github.com/quarkusio/quarkus-workshops/tree/main/quarkus-workshop-super-heroes/super-heroes/ui-super-heroes#swagger-codegen
```

**Comment by edeandrea** [comment]
Thanks @agoncal!

@rafaeltuelho Does [this](https://github.com/quarkusio/quarkus-super-heroes/issues/172#issuecomment-1315129245) answer your question?

**Comment by rafaeltuelho** [comment]
Yep! Thanks @edeandrea and @agoncal

**Comment by edeandrea** [comment]
Good to hear! I'm going to close this issue.
