### ISSUE TITLE
Add distributed tracing

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus-super-heroes#2]
Add distributed tracing within and between each of the services. This would also need to add Jaeger to the infra which gets deployed.

**Comment by edeandrea** [comment]
Hi @CarlosPanarello thanks for taking interest!

I'll let @cescoffier weigh in as well, but I did start working with the OpenTelemetry extensions but quickly found that they just  aren't feature complete yet, especially on the reactive side.

Because of that I would probably suggest the OpenTracing extensions, unless @cescoffier thinks otherwise.

> Infra part, it will be adding jaeger in docker-compose files and k8s configs right?

That is correct. Please let me know if you have any questions on how things are structured. The main `deploy` directory and the `deploy` directories inside all the application folders are generated, so necessary changes would be in `src/main/kubernetes` and `src/main/docker-compose` within each of the applications, plus the `monitoring` folder at the project root.

@cescoffier maybe it makes sense to combine prometheus and jaeger together into a single "monitoring" thing? Or do you think it would be better to keep them separate?

**Comment by cescoffier** [comment]
I would say... let's ask @radcortez :-)

**Comment by edeandrea** [comment]
I did a while back - https://github.com/quarkusio/quarkus/discussions/22653

**Comment by radcortez** [comment]
While indeed the OTel work is still underway, I believe we should move as quickly as possible to it. OpenTracing is completely abandoned. Just recently we had to duplicate some of their libraries to fix issues because no one is looking into the OpenTracing repositories anymore. Using OpenTracing will just perpetuate this state of things.

I'm happy to help with the OTel configuration here and raise all gaps to prioritize the support in Quarkus.

**Comment by edeandrea** [comment]
Hey @radcortez I started working on this today & I opened 2 issues related to OpenTelemetry:
- https://github.com/quarkusio/quarkus/issues/26301
- https://github.com/quarkusio/quarkus/issues/26304

**Comment by radcortez** [comment]
Sure, I'll have a look.

**Comment by luneo7** [comment]
#26301 is actually the same thing as https://github.com/quarkusio/quarkus/issues/26258

**Comment by edeandrea** [comment]
I also opened https://github.com/quarkusio/quarkus/issues/26333

I was experiencing that with the `rest-fights` service as I was integrating opentelemetry into it. I found this when I was looking at the traces when the `rest-fights` service makes calls to both `rest-heroes` & `rest-villains`. I dumbed it down into a more simple reproducer.

**Comment by edeandrea** [comment]
And I also found this: https://github.com/quarkusio/quarkus/discussions/26353

I'm not sure if I'm doing something wrong or if there is actually something wrong.
