### ISSUE TITLE
Missing spaces in the super powers

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-super-heroes#22]
The `imports.sql` had an _import_ issue. The superpowers are missing some spaces.
For example: `WillInvisibilityLongevityMaster`. It should be "Will Invisibility Longevity Master"

**Comment by edeandrea** [comment]
That's what was on the most recent export I got from

https://raw.githubusercontent.com/cescoffier/supes-data/master/heroes-import.sql

https://raw.githubusercontent.com/cescoffier/supes-data/master/villains-import.sql

**Comment by cescoffier** [comment]
Yeah, I would need to regenerate these files too.

**Comment by edeandrea** [comment]
I notice there are some json files as well in that repo you have. Do those json files contain all the same records? It looks like it uses an array of strings and the powers have spaces in them.

If so, I bet I could write a quick script which re-generates the sql files from that.

**Comment by edeandrea** [comment]
Maybe this is also a good opportunity to separate the persistence model from the view model and use Mapstruct in between?

Maybe the persistence model stores the powers as a `List<String>` and the view model just uses `String`?

**Comment by edeandrea** [comment]
@cescoffier How's this?

https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/all-heroes.sql

https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/all-villains.sql

I pulled in the json files in your repo into the `characterdata` branch and then I created a script which generates the SQL files from the json files: https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/generate-sql-from-json.groovy

It can be run like `groovy generate-sql-from-json.groovy all-heroes.json all-heroes.sql hero` (for Heroes) and `groovy generate-sql-from-json.groovy all-villains.json all-villains.sql villain` (for Villains).

If this looks good to you I'll move it into the `main` branch and re-run my script which randomly grabs 100 of each

**Comment by cescoffier** [comment]
Looks great! What about using JBang instead of Groovy? It will make @maxandersen happy.

**Comment by edeandrea** [comment]
Java is so over-complicated when it comes to things like this :) You see how simple it is in Groovy since dealing with structured data is part of the language itself.
