### ISSUE TITLE
Redis Cache Implementation

### ISSUE THREAD

**Issue by maranza** [quarkusio/quarkus-super-heroes#225]
I have noticed there are no examples of Redis Cache integrated into Quarkus.
Can we request the best practice sample within this project where we use 
Redisson and Jedis clients
And even perhaps showcase how we would connect to AWS Elasticache redis

**Comment by edeandrea** [comment]
Hi thank you for the comment!

Currently there is no redis caching in this sample. We can see if it might be a potential fit someplace within the architecture in the future.

For now, the Quarkus guides, documentation, and some articles would be your best bet:
- [Using the redis client](https://quarkus.io/guides/redis)
- [Redis extension reference guide](https://quarkus.io/guides/redis-reference)
- [How to cache with Redis](https://quarkus.io/blog/redis-api-intro)
- [Redis Job Queues](https://quarkus.io/blog/redis-job-queue-reloaded)

**Comment by edeandrea** [comment]
I'm going to go ahead and close this issue for now.
