### ISSUE TITLE
Drop Java 11

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus-super-heroes#283]
What would folks think about dropping Java 11 and only have a Java 17-based source tree? I know Quarkus supports both 11 & 17.

Dropping Java 11 would allow us to do a lot of cleanup and it would also significantly speed up all the CI/CD processes.

@cescoffier / @agoncal / @holly-cummins / @maxandersen thoughts?

**Comment by cescoffier** [comment]
+1 - most of my demos are using java 17 or 20 (and one using my own build of 21)

**Comment by someth2say** [comment]
Yes, please! 
I see no value in showcasing Java 11.

**Comment by edeandrea** [comment]
I'm going to take on this issue and drop java 11 from the project. I'll leave the automation in place to support building multiple java versions in case in the future we want to build java 17 & java 21 for example.

**Comment by cescoffier** [comment]
Can’t we try the EA version of 21?

Clement

**Comment by edeandrea** [comment]
> Can’t we try the EA version of 21?

But there isn't an image available on `registry.access.redhat.com`. We'd have to have a completely different `Dockerfile` for 21, plus we'd have to make sure the GitHub action workflows properly knew how to pull down EA versions.

And then what about native? We'd be using 21 for jvm but 17 for native?

I think I'd rather just keep everything at 17 until 21 is "official"?

**Comment by cescoffier** [comment]
Ah yes! Sorry forgot that it’s a deployment target, not only a compilation
target.

So using 20 might be a good idea until 21 gets released.

**Comment by edeandrea** [comment]
> So using 20 might be a good idea until 21 gets released.

That has the same problem. There is no image on `registry.access.redhat.com` for openjdk-20.
