### ISSUE TITLE
Switching from jmeter to hyperfoil

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-super-heroes#286]
In the past few months, we have seen countless broken benchmarks.  Most of them were blindly using jmeter without understanding coordinated omission problems. Basically: do not trust jmeter. 

It would be great to switch to hyperfoil (which we can trust) instead of jmeter to avoid such a problem and have a place showing how to do it.

I'm sure @franz1981 would be happy to help on this one (as he has to explain the problem every time).

**Comment by franz1981** [comment]
Thanks @cescoffier very true! 
@johnaohara and @edeandrea are already working on a version of this that's using hyperfoil (yay!) 
- I can happily review both results and benchmarking scripts for sure

**Comment by geoand** [comment]
@edeandrea would you be able to make the change after Devoxx UK?

**Comment by edeandrea** [comment]
@geoand it's not as simple as just "make the switch" :) but yes it's being worked on (when there's time) :)
