### ISSUE TITLE
Clean up various kubernetes profiles config

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus-super-heroes#300]
All the various kubernetes profile config within each application's configuration files could be made a whole bunch cleaner by using config syntax like `%kubernetes,openshift,knative.property=value`, which was introduced recently within Quarkus.

**Comment by holly-cummins** [comment]
Oh, good point!

**Comment by edeandrea** [comment]
This will depend on https://github.com/quarkusio/quarkus/pull/34487 and https://github.com/quarkusio/quarkus/issues/34025

**Comment by edeandrea** [comment]
Based on https://github.com/quarkusio/quarkus/pull/34487 and https://github.com/quarkusio/quarkus/issues/34025, the implementation of this will change a bit. We will define everything at the `quarkus.kubernetes` and then only add `quarkus.openshift/minikube/knative/etc` for things that need to be overridden, or that don't exist in `quarkus.kubernetes.*`.
