### ISSUE TITLE
Introduce Java 21

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus-super-heroes#376]
Now that Java 21 is out, run all of the automation & produce Java 17 & 21 images for all the apps.

One note is that the [Mandrel builder image](https://quay.io/repository/quarkus/ubi-quarkus-mandrel-builder-image?tab=tags&tag=latest) doesn't yet have a Java 21 image, so for now we'll have to use the [GraalVM CE builder image](https://quay.io/repository/quarkus/ubi-quarkus-graalvmce-builder-image?tab=tags)

**Comment by cescoffier** [comment]
At the moment, we can’t really use java 21 in native as we do not have the
mandrel 21 yet.

So I would keep java 17 for native.

**Comment by edeandrea** [comment]
Well for now for native I would switch to use quay.io/quarkus/ubi-quarkus-graalvmce-builder-image

**Comment by cescoffier** [comment]
You can, it’s what I recommend. However we are not done with all the
testing. In other words, use it are your own risks 🤪

**Comment by edeandrea** [comment]
Right. I get that.

What about building a container image for jvm on 21? There is no openjdk-21 image on registry.access.redhat.com. For now maybe I'll try to build my own on ubi-minimal.

**Comment by edeandrea** [comment]
This is what I'm going with for now...

```dockerfile
FROM azul/zulu-openjdk:21-jre
RUN mkdir -p /deployments/lib && \
    mkdir -p /deployments/app && \
    mkdir -p /deployments/quarkus

ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en'

# We make four distinct layers so if there are application changes the library layers can be re-used
COPY target/quarkus-app/lib/ /deployments/lib/
COPY target/quarkus-app/*.jar /deployments/
COPY target/quarkus-app/app/ /deployments/app/
COPY target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8087

ENTRYPOINT ["java", "-jar", "/deployments/quarkus-run.jar", "-Dquarkus.http.host=0.0.0.0", "-Djava.util.logging.manager=org.jboss.logmanager.LogManager"]
```

**Comment by edeandrea** [comment]
Hey @cescoffier now that https://catalog.redhat.com/software/containers/ubi9/openjdk-21-runtime/6501ce769a0d86945c422d5f, `quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21`, and https://github.com/graalvm/mandrel/releases/tag/mandrel-23.1.1.0-Final are all out, do you think we should switch the superheroes to ONLY have Java 21?

Or should we have deployments for both 17 & 21, like we used to do for 11 & 17. We would only use 21 for native - I'm thinking just on the JVM side.

I'm almost to the point of saying forget about 17, just go fully to 21.

@holly-cummins / @agoncal / @cescoffier WDYT?
