### ISSUE TITLE
Switch narration app to use quarkus-langchain4j

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus-super-heroes#421]
Currently the `rest-narration` application uses the [Microsoft Semantic Kernel for Java](https://devblogs.microsoft.com/semantic-kernel/introducing-semantic-kernel-for-java/) library for connecting to the OpenAI providers.

There are some drawbacks to using this library in Quarkus:
1. It does not support native compilation (see https://github.com/microsoft/semantic-kernel/issues/2885) 
2. It is "heavy" and is built on top of project reactor and not Java 9 Flows
3. It is very difficult to test. You can not use WireMock for mocking calls due to the fact the Azure client thats baked in requires the use of specific Microsoft certificates that aren't provided. Because of this we have to revert to object-based mocking, which means having to know/understand the internals of the Semantic Kernel library to know & understand how to mock it

Instead, we should use the [Quarkus Langchain4J extension](https://docs.quarkiverse.io/quarkus-langchain4j/dev/openai.html). This would also make it super easy to use a local LLM instead of invoking a remode instance. Its also more advanced than Semantic Kernel, has more functionality, the API is nicer (no project reactor), and it has a larger community behind it.

**Comment by geoand** [comment]
@edeandrea would you be able to give me the URL the application uses when it hits OpenAI?

Asking because I tried something really quick with Langchain4j but I am getting 404s

**Comment by edeandrea** [comment]
I really have no idea what url it hits currently. It's baked into the semantic kernel API somewhere.....

**Comment by geoand** [comment]
The URL. I was hoping that semantic kernel has some debugging you can use

**Comment by edeandrea** [comment]
Which URL though? The URL it uses for the Azure OpenAI service or for OpenAI.net?

**Comment by edeandrea** [comment]
It would be something like https://<cognitive-service-endpoint>/deployments/<deployment-name>/completions?api-version=<api-version>

**Comment by geoand** [comment]
Once https://github.com/quarkiverse/quarkus-langchain4j/pull/39 is in and we do a `0.2.0` release, the switch should be possible and the move to `quarkus-langchain4j-azure-openai` should make the narration service a lot simpler.

**Comment by edeandrea** [comment]
Per the conversation in quarkiverse/quarkus-langchain4j#39, unfortunately for now we can not bring that extension into the mix within this application due to the fact that this app currently supports integration with both Azure OpenAI and OpenAI.net. The Quarkus Langchain4j extension currently only supports a single provider.

Perhaps in the future it might support multiple providers via configuration.

**Comment by edeandrea** [comment]
Nevermind I found `quarkus.langchain4j.chat-model.provider`!
