### ISSUE TITLE
Introduce a different database for each microservice ?

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus-super-heroes#6]
All three Villain, Hero and Fight microservices use a Postgres database. What about having a different database type for each microservice?

We could use Postgres, MySQL and MariaDB, for example.

**Comment by edeandrea** [comment]
We certainly could. It would have an effect on running the system via docker compose though. Right now only 1 DB instance is started and 3 schemas are created. That would have to change.

**Comment by agoncal** [comment]
Or maybe have a simpler setup when using docker compose (only one instance of Postgres) and a more complex one when doing K8s ?

**Comment by edeandrea** [comment]
But then the apps would have to have each of the extensions. Isn't that a Quarkus anti-pattern?

By anti-pattern I mean it would be ok to have more than one datasource extension present if the app communicated with more than 1 datasource, but to switch datasource types between environments? Some of the datasource config is fixed at build time.

**Comment by edeandrea** [comment]
BTW I'm not against the idea, just playing devil's advocate and thinking out loud about the repercussions.

**Comment by agoncal** [comment]
You're right. We could use Quarkus profiles but that could be cumbersome. I'll give it a try and submit a PR is I come up with something that ends up easy to run on docker compose and no too difficult on K8s

**Comment by edeandrea** [comment]
Let me know if you have any questions about the setup and how the k8s/docker compose files are generated. I tried to be detailed in the documentation, but if something doesn't make sense or the documentation needs to be updated I'm happy to modify the docs (or take PRs :) ).

**Comment by Jenriksen** [comment]
Looking at eShopOnContainers project from Microsoft might give some ideas, they have implemented a full set of microservices with different databases as well (I believe their older versions of the repo used an even wider range of different db)

**Comment by edeandrea** [comment]
I was thinking about Mongo and/or Cassandra? Although Cassandra doesn't yet have a Dev Service (see datastax/cassandra-quarkus#199) so I'd be hesitant to use it.

**Comment by Jenriksen** [comment]
So MongoDB it is then. I will see if I can find the time to create a PR
this week.

tor. 24. feb. 2022 13.43 skrev Eric Deandrea ***@***.***>:

**Comment by edeandrea** [comment]
Awesome! Thanks for taking an interest @Jenriksen!

@agoncal / @cescoffier thoughts?

**Comment by edeandrea** [comment]
Maybe the fight service makes the most sense/is the least invasive?

**Comment by agoncal** [comment]
I like the idea of having several types of databases, APIs and so on. As @edeandrea mentioned, MongoDB has DevServices (which makes lives easier in dev). So, if Cassandra does not have DevServices (yet?), Mongo is a good choice

**Comment by cescoffier** [comment]
I would go for a noSQL DB. Mongo is fine, Redis might be interesting too. 

Mongo is closer to what we did in the other microservices (we have a Panache layer). So, I would go mongo.
