### ISSUE TITLE
Weird CORS bug when pressing "fights"

### ISSUE THREAD

**Issue by psirdev** [quarkusio/quarkus-super-heroes#687]
**Describe the bug**
CORS error on "fights" endpoint fetched. 

**To Reproduce**
1. Execute rest-heroes, rest-villains, rest-fights with "./mvnw quarkus:dev"
2. Launch UI (http://localhost:8080)
3. Click "Fight"
4. See error on network (and nothing on front)

**Expected behavior**
Fight!

**Screenshots**
![image](https://github.com/quarkusio/quarkus-super-heroes/assets/24595118/9f1efb8c-0d66-4f7b-adef-5056a8293e07)
![image](https://github.com/quarkusio/quarkus-super-heroes/assets/24595118/d5b63186-b7a8-4799-be01-c8f5b056f29f)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 121.0.6167.161

**Additional context**
It's weird because with "randomfighters" doesn't happen.

![image](https://github.com/quarkusio/quarkus-super-heroes/assets/24595118/f682d9ff-1bd8-4e31-9059-e4ff6cc404fe)

CORS is setted BTW:

![image](https://github.com/quarkusio/quarkus-super-heroes/assets/24595118/bf21be57-c451-4860-9937-8ae192825112)

![image](https://github.com/quarkusio/quarkus-super-heroes/assets/24595118/70a93a0f-c6ec-42a9-be32-1830db4e56da)

**Comment by psirdev** [comment]
> When you launched fights, did you use `-Dquarkus.profile=no-microcks` (see https://github.com/quarkusio/quarkus-super-heroes/tree/main/rest-fights#integration-with-microcks)?
> 
> By default if you just to `./mvnw quarkus:dev` on rest-fights, it will not talk to heroes/villains and will serve "canned" responses.

Very fast response Eric, wow!

I tried that, works the same, but the UI just points to the microcks endpoint. Maybe I need to change the UI endpoint and do a research in the READMEs before doing some testing.

It's not the topic of this issue, but... any video or tutorial for the Super Heroes repo?

Thanks!

**Comment by edeandrea** [comment]
I just started all the apps manually

- In `grpc-locations`: `./mvnw clean quarkus:dev`
- In `rest-villains`: `./mvnw clean quarkus:dev`
- In `rest-heroes`: `./mvnw clean quarkus:dev`
- In `rest-fights`: `./mvnw clean quarkus:dev -Dquarkus.profile=no-microcks`
- In `ui-super-heroes`: `./mvnw clean quarkus:dev -Dquarkus.profile=no-microcks`

And when I bring up the UI (http://localhost:8080) everything seems to work fine. No CORS issues.

Can you tell me a little bit more about how you are running the UI? Are you doing a `docker run`? Or are you starting via `./mvnw quarkus:dev`?

> It's not the topic of this issue, but... any video or tutorial for the Super Heroes repo?

There are a few resources...
- https://youtube.com/live/W_QREL1nEGI
- https://youtu.be/H9yK0xnExeA
- https://youtu.be/7M0Tvlx-GTA
- https://quarkus.io/blog/quarkus-superheroes-to-the-rescue/

**Comment by edeandrea** [comment]
Actually you know what - when I start up the UI with just `./mvnw clean quarkus:dev` and when I do a FIGHT, I do see the CORS issue...

I've created https://github.com/microcks/microcks-quarkus/issues/22 for some guidance.

**Comment by psirdev** [comment]
> I just started all the apps manually
> 
> * In `grpc-locations`: `./mvnw clean quarkus:dev`
> * In `rest-villains`: `./mvnw clean quarkus:dev`
> * In `rest-heroes`: `./mvnw clean quarkus:dev`
> * In `rest-fights`: `./mvnw clean quarkus:dev -Dquarkus.profile=no-microcks`
> * In `ui-super-heroes`: `./mvnw clean quarkus:dev -Dquarkus.profile=no-microcks`
> 
> And when I bring up the UI (http://localhost:8080) everything seems to work fine. No CORS issues.
> 
> Can you tell me a little bit more about how you are running the UI? Are you doing a `docker run`? Or are you starting via `./mvnw quarkus:dev`?
> 
> > It's not the topic of this issue, but... any video or tutorial for the Super Heroes repo?
> 
> There are a few resources...
> 
> * https://youtube.com/live/W_QREL1nEGI
> * https://youtu.be/H9yK0xnExeA
> * https://youtu.be/7M0Tvlx-GTA
> * https://quarkus.io/blog/quarkus-superheroes-to-the-rescue/
> 
> There is also the repo's main README file, as well as the README files of all the individual applications.

Just missed the `-Dquarkus.profile=no-microcks` parameter on `ui-super-heroes` and `rest-fights`. Now works perfectly. No cors problem and #686 problem disappear. Does the order of execution matter 

Maybe too much desire on running quarkus perfectly without reading READMEs 🤣

(I need to check grpc-locations, I know)

https://i.gyazo.com/12559cefdb3e493ec8c6e4d2e098c889.png

**Comment by edeandrea** [comment]
> Does the order of execution matter?

No it doesn't.

**Comment by psirdev** [comment]
> Actually you know what - when I start up the UI with just ./mvnw clean quarkus:dev and when I do a FIGHT, I do see the CORS issue...
> 
> I've created [microcks/microcks-quarkus#22](https://github.com/microcks/microcks-quarkus/issues/22) for some guidance.

Great! I would continue without microcks for the moment. 

If you wanna close or continue this issue, your choice. Thanks!

**Comment by edeandrea** [comment]
I'll keep it open for now until I get feedback on the issue I created in microcks.

**Comment by edeandrea** [comment]
@psirdev FYI the issue has been fixed by https://github.com/microcks/microcks-quarkus/issues/22
